### ISSUE TITLE
consider actix-web and r2d2

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-validator-stack-rust#15]
this is nice: https://github.com/actix/examples/blob/master/r2d2/src/main.rs 

and especially the ability to do `web::block`, which executes sync code in a threadpool; we can also look into similar mechanisms for `tower`

another great backwards compat mechanism

considering we have redis (https://github.com/actix/examples/blob/master/actix_redis/src/main.rs), which has a pure async driver, using postgres may be minimized so that this is OK

Once tokio-postgres matures we can use it instead of `web::block`; but there's also https://github.com/actix/examples/blob/master/async_db/src/main.rs, which I suspect uses `web::block` under the hood

**This is just another option that we have; it'd be best to focus on validator, and after we implement that, get back to the sentry and re-evaluate all our options**

**Comment by elpiel** [comment]
Here's another option to consider: http://docs.rs/axum

Axum is from the tokio project and is build on top of tower, hyper & tokio - mostly what we already use, so it should be easier to transition to it.

**Comment by elpiel** [comment]
We now use `axum` #535 & we've been using `deadpool` for some time now to have database pools for Postgres (not redis) but after a lot of performance reviewing, we've figured out that the bottleneck is Postgres.

For more details see: https://gist.github.com/elpiel/12207618160ac1a4e39cb26dbabc0a26#file-performance-md
