### ISSUE TITLE
preserve original error message in adapters/ethereum

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-validator-stack-rust#260]
the ethereum adapter erases the original error messages by mapping them to messages like "Invalid keystore location provided" or "Failed to create account"

The problem with that is that the messages are untuitive, but also that they erase information

E.g. failing to read a file may be due to a non-existant file, or it could be a permission denied, or it could even be a "too many open files" error; but we just show "Invalid keystore location provided", which is unclear and even inaccurate for some of those scenarios

same goes for "Failed to create account", which happens when your passphrase is incorrect; and also for other messages

**Solution:** wrap the original error into an enum and print the enum with it's contents

**Comment by elpiel** [comment]
I've looked into this yesterday. My question is: Do we want the context as well?
If I see an error I would like to also see the context in which it was created (i.e. keystore failed to be loaded or smth)

**Comment by Ivshti** [comment]
Yes, definitely. This is why I offered an enum that preserves the context but contains the original error inside

**Comment by elpiel** [comment]
Fixed in #277
